import { createClient } from '@supabase/supabase-js';
import 'dotenv/config';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey || supabaseUrl === 'YOUR_SUPABASE_URL_HERE') {
  console.error('Por favor, configure as variáveis VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY no arquivo .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function seed() {
  console.log('Testando se a tabela "persons" existe e inserindo pessoa de exemplo...');
  
  const novaPessoa = { 
    firstname: 'João', 
    lastname: 'Silva', 
    email: 'joao.silva@exemplo.com', 
    phone: '(11) 99999-9999', 
    gender: 'male',
    image: 'https://i.pravatar.cc/150?u=joao'
  };

  const { error } = await supabase
    .from('persons')
    .insert([novaPessoa]);

  if (error) {
    console.error('\n❌ ERRO:', error.message);
    if (error.code === '42P01' || error.message.includes('relation "public.persons" does not exist')) {
      console.error('\n⚠️ A tabela "persons" ainda não foi criada no seu Supabase!');
      console.error('Você não pode criar tabelas por script no Supabase por questões de segurança (a API pública não tem essa permissão).');
      console.error('Copie e cole o seguinte comando no SQL EDITOR do painel do Supabase:\n');
      console.error(`create table persons (
  id bigint generated by default as identity primary key,
  firstname text not null,
  lastname text not null,
  email text not null,
  phone text not null,
  gender text not null,
  image text
);
alter table persons disable row level security;`);
    }
  } else {
    console.log('✅ Pessoa de exemplo ("João Silva") criada com sucesso no banco!');
  }
}

seed();
